server:
  port: 8080
spring:
  application:
    name: my_blog
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&nullCatalogMeansCurrent=true&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 15
      max-wait: 5000
      time-between-eviction-runs-millis: 90000
      min-evictable-idle-time-millis: 1800000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.jxy.my_blog.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl